class EgyptGovernorates {
  static const List<String> governorates = [
    'القاهرة',
    'الجيزة',
    'الإسكندرية',
    'الدقهلية',
    'الشرقية',
    'القليوبية',
    'كفر الشيخ',
    'الغربية',
    'المنوفية',
    'البحيرة',
    'الإسماعيلية',
    'بورسعيد',
    'السويس',
    'شمال سيناء',
    'جنوب سيناء',
    'الفيوم',
    'بني سويف',
    'المنيا',
    'أسيوط',
    'سوهاج',
    'قنا',
    'الأقصر',
    'أسوان',
    'البحر الأحمر',
    'الوادي الجديد',
    'مطروح',
    'دمياط',
  ];

  static const Map<String, String> governoratesEn = {
    'القاهرة': 'Cairo',
    'الجيزة': 'Giza',
    'الإسكندرية': 'Alexandria',
    'الدقهلية': 'Dakahlia',
    'الشرقية': 'Sharqia',
    'القليوبية': 'Qalyubia',
    'كفر الشيخ': 'Kafr El Sheikh',
    'الغربية': 'Gharbia',
    'المنوفية': 'Monufia',
    'البحيرة': 'Beheira',
    'الإسماعيلية': 'Ismailia',
    'بورسعيد': 'Port Said',
    'السويس': 'Suez',
    'شمال سيناء': 'North Sinai',
    'جنوب سيناء': 'South Sinai',
    'الفيوم': 'Faiyum',
    'بني سويف': 'Beni Suef',
    'المنيا': 'Minya',
    'أسيوط': 'Asyut',
    'سوهاج': 'Sohag',
    'قنا': 'Qena',
    'الأقصر': 'Luxor',
    'أسوان': 'Aswan',
    'البحر الأحمر': 'Red Sea',
    'الوادي الجديد': 'New Valley',
    'مطروح': 'Matrouh',
    'دمياط': 'Damietta',
  };
}