name: tahya_misr_app
description: "Tahya Misr Students Union Mobile App with clean architecture"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI & Material Design
  cupertino_icons: ^1.0.6
  material_color_utilities: ^0.11.1

  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  
  # Freezed for immutable classes
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  
  # Networking & API
  retrofit: ^4.0.3
  dio: ^5.3.3
  connectivity_plus: ^4.0.2
  
  # JSON Serialization
  json_annotation: ^4.8.1
  
  # Local Storage & Caching
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  
  # Navigation
  go_router: ^10.1.2
  
  # UI Components & Animation
  flutter_animate: ^4.2.0
  skeletonizer: ^2.1.0+1
  infinite_scroll_pagination: ^4.0.0
  
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # Utilities
  logger: ^2.0.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  intl: ^0.20.2
  readmore: ^3.0.0

  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  retrofit_generator: ^7.0.8
  json_serializable: ^6.7.1
  injectable_generator: ^2.1.6
  hive_generator: ^2.0.1
  
  # Linting
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
#
#  fonts:
#    - family: Cairo
#      fonts:
#        - asset: assets/fonts/Cairo-Regular.ttf
#        - asset: assets/fonts/Cairo-Bold.ttf
#          weight: 700